### ISSUE TITLE
Is this still a live project? Where to request API key?

### ISSUE THREAD

**Issue by paveljurca** [RaceHero/api#12]
Hi, I went over your Apiary blueprint where you referer to Basic Auth:
1) Where to get API key?
2) Is the API still v1?

Thank you for every help, cheers!

**Comment by ghidinelli** [comment]
Hi Pavel - nice to hear from you! It is still live and running. You can create an account on RaceHero and obtain an API key that way. The API is still the v1. Let us know how we can support you.
