### ISSUE TITLE
Get events of a specific organization

### ISSUE THREAD

**Issue by avvertix** [RaceHero/api#9]
Hey, many thanks for the service and for posting the API. I have a question: how do I get events only for a specific organization?

**Comment by ghidinelli** [comment]
Hi @avvertix - the API is in beta right now. The short answer to your question is you can't just yet so we might want to take this discussion offline so we can provide you extra support?

**Comment by avvertix** [comment]
For the current scope to get the events of an organization I resolved it by getting the latest events and then filter from the response on the basis of the organization name. This covered the scenario I had in mind since the event is created within a reasonable time before the events listing request, so there will be not many other events. Thanks indeed for the help, I might use the option when checking how to show to switch from two live runs

**Comment by ghidinelli** [comment]
@avvertix thanks - I've logged an enhancement request to be able to list events by organization and by venue, both of which should be available soon and will be reflected in the Swagger doc. Thanks for the feedback!  Also, mind sharing what org you're with or working for?

**Comment by avvertix** [comment]
> mind sharing what org you're with or working for?

yes, I'm on behalf of "la freccia del tempo"

**Comment by ghidinelli** [comment]
@avvertix we added this in #10 and it's in testing now. Should be in production shortly.
